spring:
  application:
    name: goorm
  datasource:
    url: jdbc:h2:mem:local;
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: embedded

#  servlet:
#    multipart:
#      max-file-size: 5MB